version: 2.1

jobs:
  build:
    docker:
      - image: node:18  # Use the official Node.js 18 image
    steps:
      - checkout
      - run:
          name: Print Working Directory
          command: pwd
      - run:
          name: List Files
          command: ls -la
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Tests
          command: npm run test   # This will run your vitest tests
      - run:
          name: Build the App
          command: npm run build
      - run:
          name: Install AWS CLI
          command: |
            apt-get update
            apt-get install -y awscli
      - run:
          name: Sync to S3
          command: |
            aws s3 sync ./dist s3://circle-ci-syndeo --delete
          
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
